version: "3"
services:
  
  mysql:
   
    image: mysql:5.6
    container_name: mysql
    restart: always
    networks:
      - wpnet
    volumes:
      - "mysql-vol:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot123
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=wpuser123  

networks:
  wpnet:    
volumes:
  mysql-vol:
