version: "3"
services:
  
  mysql:
   
    image: mysql:5.6
    container_name: mysql
    restart: always
    networks:
      - wpnet
    volumes:
      - "mysql-vol:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot123
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=wpuser123        

  wordpress:
    
    image: wordpress:latest
    container_name: wordpress
    restart: always
    networks:
      - wpnet
    volumes:
      - "wordpress-vol:/var/www/html"
    ports:
      - "80:80"
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=wpuser123
      - WORDPRESS_DB_NAME=wordpress
networks:
  wpnet:    
volumes:
  mysql-vol:
  wordpress-vol:
